/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.zohaib.ics4u.u2;

import edu.hdsb.gwss.zohaib.ics4u.u1.Library;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;

/**
 *
 * @author 1ahmadzoh
 */
public class Game1024 extends javax.swing.JFrame {

    private JLabel[][] squaresLabels;

    private int[][] squareValues;

    //Variables
    private int score;

    /**
     * Creates new form Game1024
     */
    public Game1024() {
        initComponents();

        //Put JLabels in the 2D Array
        squaresLabels = new JLabel[4][4];
        squareValues = new int[4][4];

        squaresLabels[0][0] = jLabel00;
        squaresLabels[0][1] = jLabel01;
        squaresLabels[0][2] = jLabel02;
        squaresLabels[0][3] = jLabel03;

        squaresLabels[1][0] = jLabel10;
        squaresLabels[1][1] = jLabel11;
        squaresLabels[1][2] = jLabel12;
        squaresLabels[1][3] = jLabel13;

        squaresLabels[2][0] = jLabel20;
        squaresLabels[2][1] = jLabel21;
        squaresLabels[2][2] = jLabel22;
        squaresLabels[2][3] = jLabel23;

        squaresLabels[3][0] = jLabel30;
        squaresLabels[3][1] = jLabel31;
        squaresLabels[3][2] = jLabel32;
        squaresLabels[3][3] = jLabel33;

        newGame();

    }

    private void newGame() {

        //Reset Score
        score = 0;

        for (int row = 0; row < squareValues.length; row++) {

            for (int col = 0; col < squareValues[row].length; col++) {

                squareValues[row][col] = 0;

            }

        }

        //3. Place two random
        placeRandomTwo();
        placeRandomTwo();

        refreshTiles();

        slideRight();
    }

    //4. Display
    private void placeRandomTwo() {
        //Variables
        int row = 0;
        int col = 0;
        boolean placed = false;

        while (!placed) {

            row = (int) ((Math.random()) * squareValues.length);
            col = (int) ((Math.random()) * squareValues.length);

            System.out.println("");

            if (squareValues[row][col] == 0) {

                squareValues[row][col] = 2;
                placed = true;

            } else {

                squaresLabels[row][col].setText("" + squareValues[row][col]);

            }

        }

    }

    public void refreshTiles() {
        for (int row = 0; row < squareValues.length; row++) {

            for (int col = 0; col < squareValues[row].length; col++) {

                //Check to see if its zero
                if (squareValues[row][col] == 0) {

                    squaresLabels[row][col].setText("");

                } else {

                    squaresLabels[row][col].setText(" " + squareValues[row][col]);

                    System.out.println("" + squareValues[row][col]);

                }

            }

        }

    }

    private void slideRight() {
        //For Each Row
        for (int r = 0; r < squareValues.length; r++) {

            //Pass for "Bubble" Sort
            for (int pass = 0; pass < squareValues[r].length - 1; pass++) {

                //For the second last Column 
                for (int c = squareValues[r].length - 2; c >= (0 + pass); c++) {

                    //Is the right empty
                    if (squareValues[r][c] != 0 && squareValues[r][c + 1] == 0) {

                        Library.swap(squareValues, r, c, r, r + 1);
                    }

                }

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel00 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel01 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel02 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel03 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        main.setBackground(new java.awt.Color(51, 51, 255));
        main.setForeground(new java.awt.Color(153, 255, 51));

        jLabel00.setBackground(new java.awt.Color(153, 204, 0));
        jLabel00.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel00.setText("00");
        jLabel00.setOpaque(true);
        jLabel00.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel20.setBackground(new java.awt.Color(153, 204, 0));
        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("20");
        jLabel20.setOpaque(true);
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel10.setBackground(new java.awt.Color(153, 204, 0));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("10");
        jLabel10.setOpaque(true);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel30.setBackground(new java.awt.Color(153, 204, 0));
        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("30");
        jLabel30.setOpaque(true);
        jLabel30.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel01.setBackground(new java.awt.Color(153, 204, 0));
        jLabel01.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel01.setText("01");
        jLabel01.setOpaque(true);
        jLabel01.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel11.setBackground(new java.awt.Color(153, 204, 0));
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("11");
        jLabel11.setOpaque(true);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel21.setBackground(new java.awt.Color(153, 204, 0));
        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("21");
        jLabel21.setOpaque(true);
        jLabel21.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel31.setBackground(new java.awt.Color(153, 204, 0));
        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("31");
        jLabel31.setOpaque(true);
        jLabel31.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel12.setBackground(new java.awt.Color(153, 204, 0));
        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("12");
        jLabel12.setOpaque(true);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel22.setBackground(new java.awt.Color(153, 204, 0));
        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("22");
        jLabel22.setOpaque(true);
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel02.setBackground(new java.awt.Color(153, 204, 0));
        jLabel02.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel02.setText("02");
        jLabel02.setOpaque(true);
        jLabel02.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel32.setBackground(new java.awt.Color(153, 204, 0));
        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("32");
        jLabel32.setOpaque(true);
        jLabel32.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel03.setBackground(new java.awt.Color(153, 204, 0));
        jLabel03.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel03.setText("03");
        jLabel03.setOpaque(true);
        jLabel03.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel13.setBackground(new java.awt.Color(153, 204, 0));
        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("13");
        jLabel13.setOpaque(true);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel23.setBackground(new java.awt.Color(153, 204, 0));
        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("23");
        jLabel23.setOpaque(true);
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel33.setBackground(new java.awt.Color(153, 204, 0));
        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("33");
        jLabel33.setOpaque(true);
        jLabel33.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel03, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel02, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel01, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel00, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int keyCode = evt.getKeyCode();
        switch (keyCode) {
            case KeyEvent.VK_UP:
                System.out.println("UP");
                break;
            case KeyEvent.VK_DOWN:
                System.out.println("DOWN");
// handle down 
                break;
            case KeyEvent.VK_LEFT:
                System.out.println("Left");
// handle left
                break;
            case KeyEvent.VK_RIGHT:
                System.out.println("Right");
// handle right
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game1024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game1024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game1024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game1024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game1024().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel01;
    private javax.swing.JLabel jLabel02;
    private javax.swing.JLabel jLabel03;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
